import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageLayout from "./components/Navigation/pagelayout";
import SessionProvider from "./components/SessionProvider/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" className="h-full bg-white">
      
      <body className={inter.className + "h-full"} >
        
        <SessionProvider session={session}><PageLayout>{children}</PageLayout></SessionProvider>
        </body>
    </html>
  );
}
